language: node_js
cache:
  directories:
  - ~/.npm
  - ~/node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
  - git fetch --tags
  - export TM_VERSION=$(npm run semantic-release:dry | grep "The next release version is " | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')
script:
  - npm run build:production
env:
  - NPM_TOKEN="00000000-0000-0000-0000-000000000000"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
after_success:
  # CREATE GIT TAG
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - '[[ $TRAVIS_BRANCH == "master" ]] && git tag $TM_VERSION -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"'
  - '[[ $TRAVIS_BRANCH == "master" ]] && git push --quiet https://$GITHUBKEY@github.com/darthvader666uk/futwebapp-tampermonkey $GIT_TAG > /dev/null 2>&1'
deploy:
  provider: releases
  api_key:
    secure: "itypG5lXUZkA647w7CUiagtzgr617UA640j17OFgzsChADpmilsdsEHV8afcuzts/CO+nzxbCO42X6jeBjYKEMvSSe1DInXCy9p0OcryUvTYsTM2zYvqTRn7syF5cN+2B3BTIQERk8nct+mao0p9iKDRvna9l6OI2MGLHm6nEsP/b4VmYMJwemleLY+dHeBLF1eSlEvg6sOHf8MZp6+OU78tUUUfb6+EW0+EpOomf4FG5D+XJn0Q7naMc6L4ehI8lvxcbuM7ECVgXBcw0ixnC/OS/JcpFYlNFHjTUqK/WDXWvoMkJPWff/+2SPYk0bnFJRI7LGCqF1DP0Yzn8Sz+TsNwkJ/plWNgZmq1GC1rEl3fVxHNRwQXb0Qu66BeK/5qJqsvZ1DW+96OwGPEYnUZBAqCVLK/4IHg1yDFTWsSs+sB+ECJNmRsXVF9dLluA3qtKlkujkTcrl5iNXptBx0czRwEvZmzZfEL8OS6naEIc396wEs4YT02vRsg8wp4psMW7YnetDcnVbqcNT9I0leFCSd7MKVFQLVfs5ybhXpb40Eo/+luq6N45GFMS+QazMnoyggAqtZ/g8HoCE0K+pK6YzbrboXeMui50yzMwwRWojM+XFSIKzcSOYP7AWWof66RKfOHqlBVYw8nhFsJ3xRQxzfp6528hZeJpWvRBFzHjbU="
  file:
    - dist/fut-enhancer.user.js
  skip_cleanup: true
